# fog_credentials.yml
default:
  aws_access_key_id: 'AKIAJCKBMLBHTPYHSFKQ'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'